[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"

members = [
    "crates/bevy_15",
    "crates/bevy_14",
    "crates/bevy_13",
    "crates/common",
]

[workspace.dependencies]
common = { path = "./crates/common" }
